### ISSUE TITLE
Omeka page error

### ISSUE THREAD

**Issue by SteveMarvin** [jamiefolsom/Neatline-Archive#10]
Entering a bad URL creates an Omeka error (404).

http://neatline-staging.herokuapp.com/neatline/show/london/zorp

OR

http://neatline-staging.herokuapp.com/neatline/show/london/admin

![screen shot 2017-03-16 at 11 09 35 am](https://cloud.githubusercontent.com/assets/18423533/24003138/0e298512-0a39-11e7-8f9a-3dc70b7b96e8.png)

```
exception 'Zend_Controller_Dispatcher_Exception' with message 'Invalid controller specified (show)' in /app/application/libraries/Zend/Controller/Dispatcher/Standard.php:248
Stack trace:
#0 /app/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /app/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#2 /app/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#3 /app/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#4 /app/index.php(23): Omeka_Application->run()
#5 {main}
```

**Comment by jamiefolsom** [comment]
Good catch -- I imagine there's a way to specify a nicer 404 page in Omeka. I will have a look.
